#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: torrdlna
# Runs the MiniDLNA daemon
# ==============================================================================
# shellcheck disable=SC1091

# Run the Tor daemon
exec minidlnad
